// pce-core stats — TypeScript mirror of src/apex_router/core/stats.py (the in-engine subset).
// Parity: tests/core_stats.test.ts against fixtures generated by apex_router.core.fixtures.
import type { Welford, WelfordCov } from '../../types/index.d.ts'

export const welfordNew = (): Welford => ({ n: 0, mean: 0, m2: 0 })

export function welfordPush(w: Welford, x: number): Welford {
  const n = w.n + 1
  const delta = x - w.mean
  const mean = w.mean + delta / n
  return { n, mean, m2: w.m2 + delta * (x - mean) }
}

export const welfordVariance = (w: Welford): number => (w.n > 1 ? w.m2 / (w.n - 1) : 0)

export function welfordCovNew(d: number): WelfordCov {
  return {
    n: 0,
    mean: Array.from({ length: d }, () => 0),
    c: Array.from({ length: d }, () => Array.from({ length: d }, () => 0)),
  }
}

export function welfordCovPush(s: WelfordCov, x: readonly number[]): WelfordCov {
  const n = s.n + 1
  const delta = x.map((xi, i) => xi - s.mean[i]!)
  const mean = s.mean.map((m, i) => m + delta[i]! / n)
  const after = x.map((xi, i) => xi - mean[i]!)
  const c = s.c.map((row, i) => row.map((cij, j) => cij + delta[i]! * after[j]!))
  return { n, mean, c }
}

export const covariance = (s: WelfordCov): number[][] => s.c.map(row => row.map(cij => (s.n > 1 ? cij / (s.n - 1) : 0)))

export const ewma = (prev: number | null, x: number, a = 0.2): number => (prev === null ? x : a * x + (1 - a) * prev)

export const halfLife = (a: number): number => Math.log(0.5) / Math.log(1 - a)

export const Q16 = 65536

export const toQ16 = (x: number): number => Math.floor(x * Q16 + 0.5)

export function ewmaQ16(prev: number | null, x: number, aQ16 = 13107): number {
  const xq = toQ16(x)
  return prev === null ? xq : prev + Math.trunc(((xq - prev) * aQ16) / Q16)
}

export function wilson(k: number, n: number, z = 1.96): [number, number] {
  if (n <= 0) throw new RangeError('n must be positive')
  const pHat = k / n
  const zSq = z * z
  const center = (pHat + zSq / (2 * n)) / (1 + zSq / n)
  const half = (z / (1 + zSq / n)) * Math.sqrt((pHat * (1 - pHat)) / n + zSq / (4 * n * n))
  return [Math.max(0, center - half), Math.min(1, center + half)]
}

export function nearestRank(sorted: readonly number[], q: number): number | null {
  if (sorted.length === 0) return null
  let rank = Math.ceil(q * sorted.length)
  rank = Math.max(1, Math.min(rank, sorted.length))
  return sorted[rank - 1]!
}
