// Generated by `python -m apex_router.core.fixtures --write` from pce-core. Do not edit.
export const CLASSIFY = [
 [
  "Explore",
  "anything at all",
  null,
  "explore"
 ],
 [
  null,
  "Review the diff for bugs",
  null,
  "review"
 ],
 [
  "general-purpose",
  "Implement backend Task 3: pressure",
  null,
  "generate"
 ],
 [
  "general-purpose",
  "Why does the test fail",
  null,
  "debug"
 ],
 [
  null,
  "Rename the helpers",
  null,
  "refactor"
 ],
 [
  null,
  "Plan the migration",
  null,
  "explore"
 ],
 [
  null,
  "audit the auth flow",
  null,
  "review"
 ],
 [
  null,
  "verify claims in the report",
  null,
  "review"
 ],
 [
  null,
  "fix flaky test",
  null,
  "generate"
 ],
 [
  null,
  "root cause the crash",
  null,
  "debug"
 ],
 [
  null,
  "summarize the report",
  null,
  "explore"
 ],
 [
  "code-reviewer",
  "look at this",
  null,
  "explore"
 ],
 [
  null,
  "Debug the proxy",
  "and then refactor it",
  "debug"
 ],
 [
  null,
  "x",
  "please review the change",
  "review"
 ],
 [
  null,
  null,
  null,
  "explore"
 ],
 [
  "Plan",
  "anything",
  null,
  "explore"
 ],
 [
  "debug",
  "",
  null,
  "debug"
 ],
 [
  null,
  "Build the CLI",
  null,
  "generate"
 ],
 [
  null,
  "rewrite the parser",
  null,
  "explore"
 ],
 [
  null,
  "reviewing PR 12",
  null,
  "review"
 ],
 [
  "general-purpose",
  "Generate fixtures",
  null,
  "generate"
 ],
 [
  null,
  "explain the cache",
  "why is it slow",
  "debug"
 ]
]
