// Generated by `python -m apex_router.core.fixtures --write` from pce-core. Do not edit.
export const CORE = {
 "anomaly": {
  "V": [
   [
    1.0,
    0.0,
    0.0
   ],
   [
    0.0,
    1.0,
    0.0
   ]
  ],
  "cases": [
   [
    [
     2.0,
     1.0,
     3.0
    ],
    9.0,
    2.0
   ],
   [
    [
     0.5,
     -1.0,
     0.2
    ],
    0.04000000000000001,
    1.0625
   ],
   [
    [
     0.0,
     0.0,
     0.0
    ],
    0.0,
    0.0
   ]
  ],
  "corr": [
   [
    1.0,
    0.3333333333333333,
    0.25
   ],
   [
    0.3333333333333333,
    1.0,
    0.3333333333333333
   ],
   [
    0.25,
    0.3333333333333333,
    1.0
   ]
  ],
  "cov": [
   [
    4.0,
    2.0,
    0.5
   ],
   [
    2.0,
    9.0,
    1.0
   ],
   [
    0.5,
    1.0,
    1.0
   ]
  ],
  "explain": [
   [
    10.0,
    1.0,
    [
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     11
    ],
    [
     1.0,
     2.0
    ],
    {
     "q": 0.9,
     "score": 0.9,
     "t2": 0.5,
     "term": "Q"
    }
   ],
   [
    0.0,
    3.0,
    [
     1.0
    ],
    [
     1.0,
     2.0
    ],
    {
     "q": 0.0,
     "score": 1.0,
     "t2": 1.0,
     "term": "T2"
    }
   ],
   [
    5.0,
    5.0,
    [],
    [],
    {
     "q": 0.0,
     "score": 0.0,
     "t2": 0.0,
     "term": "Q"
    }
   ]
  ],
  "mad": {
   "mad": 1.0,
   "median": 3.0,
   "robust": [
    [
     1.0,
     -1.349
    ],
    [
     2.0,
     -0.6745
    ],
    [
     3.0,
     0.0
    ],
    [
     4.0,
     0.6745
    ],
    [
     100.0,
     65.4265
    ]
   ],
   "xs": [
    1.0,
    2.0,
    3.0,
    4.0,
    100.0
   ]
  },
  "pca": {
   "values": [
    1.612695829613317,
    0.7500000000000001
   ],
   "vectors": [
    [
     0.5604255742993327,
     0.6097920558211015,
     0.560425574299333
    ],
    [
     0.7071067811865476,
     3.176426322190804e-16,
     -0.7071067811865476
    ]
   ]
  },
  "scales": {
   "rows": [
    [
     1.0,
     -4.0,
     0.0
    ],
    [
     2.0,
     2.0,
     0.0
    ]
   ],
   "scales": [
    2.0,
    4.0,
    1
   ]
  },
  "sd": [
   2.0,
   3.0,
   1.0
  ],
  "values": [
   4.0,
   1.0
  ]
 },
 "cells": {
  "all_pass_35": {
   "final": {
    "above": 0,
    "below": 0,
    "cusum": 0.0,
    "n": 36,
    "p0": 1.0,
    "pass": 36,
    "state": "READY",
    "winN": 6,
    "winPass": 6
   },
   "min_n": 30,
   "seq": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
   ],
   "states": [
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "READY",
    "READY"
   ],
   "target": 0.9
  },
  "anomaly_not_regime": {
   "final": {
    "above": 0,
    "below": 0,
    "cusum": 1.3070158058105008,
    "n": 50,
    "p0": 1.0,
    "pass": 49,
    "state": "READY",
    "winN": 0,
    "winPass": 0
   },
   "min_n": 30,
   "seq": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0
   ],
   "states": [
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY"
   ],
   "target": 0.9
  },
  "cusum_small_regression": {
   "final": {
    "above": 0,
    "below": 0,
    "cusum": 5.228063223242003,
    "n": 80,
    "p0": 1.0,
    "pass": 76,
    "state": "DRIFTING",
    "winN": 0,
    "winPass": 0
   },
   "min_n": 30,
   "seq": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0
   ],
   "states": [
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "DRIFTING"
   ],
   "target": 0.9
  },
  "floor_29": {
   "final": {
    "above": 0,
    "below": 0,
    "cusum": 0.0,
    "n": 29,
    "p0": null,
    "pass": 29,
    "state": "WARMING",
    "winN": 9,
    "winPass": 9
   },
   "min_n": 30,
   "seq": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
   ],
   "states": [
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING"
   ],
   "target": 0.9
  },
  "floor_target_085": {
   "final": {
    "above": 0,
    "below": 0,
    "cusum": 0.0,
    "n": 31,
    "p0": 1.0,
    "pass": 31,
    "state": "READY",
    "winN": 1,
    "winPass": 1
   },
   "min_n": 30,
   "seq": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
   ],
   "states": [
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "READY",
    "READY"
   ],
   "target": 0.85
  },
  "rebaseline": {
   "final": {
    "above": 0,
    "below": 0,
    "cusum": 0.0,
    "n": 3,
    "p0": null,
    "pass": 3,
    "state": "WARMING",
    "winN": 3,
    "winPass": 3
   },
   "min_n": 30,
   "seq": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1
   ],
   "states": [
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "COLD",
    "WARMING",
    "WARMING",
    "WARMING"
   ],
   "target": 0.9
  },
  "streak_then_restore": {
   "final": {
    "above": 0,
    "below": 0,
    "cusum": 0.0,
    "n": 90,
    "p0": 1.0,
    "pass": 86,
    "state": "READY",
    "winN": 0,
    "winPass": 0
   },
   "min_n": 30,
   "seq": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
   ],
   "states": [
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "WARMING",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "READY",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "DRIFTING",
    "READY"
   ],
   "target": 0.9
  }
 },
 "cost": {
  "budget": [
   [
    5.0,
    360.0,
    10.0,
    {
     "burn": 2.0,
     "minutesToExhaust": 360.0
    }
   ],
   [
    0.0,
    10.0,
    10.0,
    {
     "burn": 0.0,
     "minutesToExhaust": null
    }
   ],
   [
    12.0,
    60.0,
    10.0,
    {
     "burn": 28.800000000000004,
     "minutesToExhaust": 0.0
    }
   ],
   [
    1.0,
    0.0,
    10.0,
    null
   ]
  ],
  "fit": {
   "a": 0.021199981626688486,
   "b": 2.965714709713749e-05,
   "n": 6,
   "r2": 0.9993544437642354,
   "trend": -4.239994633765359e-09
  },
  "xs": [
   1000,
   2000,
   3000,
   4000,
   5000,
   6000
  ],
  "ys": [
   0.051,
   0.079,
   0.112,
   0.139,
   0.171,
   0.198
  ]
 },
 "drift": {
  "cusum": {
   "trace": [
    [
     1.0,
     false
    ],
    [
     2.0,
     false
    ],
    [
     3.0,
     false
    ],
    [
     4.0,
     false
    ],
    [
     5.0,
     true
    ],
    [
     4.5,
     true
    ],
    [
     4.0,
     false
    ],
    [
     3.5,
     false
    ],
    [
     6.0,
     true
    ],
    [
     3.5,
     false
    ]
   ],
   "zs": [
    -1.5,
    -1.5,
    -1.5,
    -1.5,
    -1.5,
    0.0,
    0.0,
    0.0,
    -3.0,
    2.0
   ]
  },
  "penalty": {
   "scores": [
    1,
    9,
    1,
    1.5,
    3,
    5,
    7,
    1,
    1,
    1,
    1
   ],
   "trace": [
    [
     1,
     "COLD",
     0
    ],
    [
     9,
     "COLD",
     0
    ],
    [
     1,
     "WARM",
     0
    ],
    [
     1.5,
     "WARM",
     0
    ],
    [
     3,
     "WARM",
     0
    ],
    [
     5,
     "DRIFTING",
     7
    ],
    [
     7,
     "DRIFTING",
     10
    ],
    [
     1,
     "DRIFTING",
     0
    ],
    [
     1,
     "DRIFTING",
     0
    ],
    [
     1,
     "WARM",
     0
    ],
    [
     1,
     "WARM",
     0
    ]
   ]
  },
  "variance_l1": [
   [
    [
     3.0,
     1.0
    ],
    [
     2.0,
     2.0
    ],
    0.5
   ],
   [
    [
     5.0,
     3.0,
     2.0
    ],
    [
     4.0,
     4.0,
     2.0
    ],
    0.2
   ],
   [
    [
     0.0
    ],
    [
     1.0
    ],
    0.0
   ]
  ]
 },
 "ewma": {
  "a": 0.2,
  "out": [
   10,
   10.2,
   9.96,
   9.968,
   17.9744,
   24.779519999999998,
   29.623616000000002,
   33.898892800000006,
   29.119114240000005,
   25.295291392000006
  ],
  "q16": [
   655360,
   668467,
   652739,
   653263,
   1177962,
   1623937,
   1941397,
   2221580,
   1908341,
   1657749
  ],
  "xs": [
   10,
   11,
   9,
   10,
   50,
   52,
   49,
   51,
   10,
   10
  ]
 },
 "has_gap": [
  [
   [
    3.0,
    1.0
   ],
   1,
   true
  ],
  [
   [
    2.0,
    2.0
   ],
   1,
   false
  ],
  [
   [
    3.0,
    1.0
   ],
   0,
   false
  ],
  [
   [
    5.0,
    4.0,
    1.0
   ],
   2,
   true
  ]
 ],
 "jacobi": [
  {
   "A": [
    [
     2.0,
     1.0
    ],
    [
     1.0,
     2.0
    ]
   ],
   "values": [
    2.9999999999999996,
    0.9999999999999998
   ],
   "vectors": [
    [
     0.7071067811865475,
     0.7071067811865475
    ],
    [
     0.7071067811865475,
     -0.7071067811865475
    ]
   ]
  },
  {
   "A": [
    [
     4.0,
     0.0,
     0.0
    ],
    [
     0.0,
     1.0,
     0.0
    ],
    [
     0.0,
     0.0,
     9.0
    ]
   ],
   "values": [
    9.0,
    4.0,
    1.0
   ],
   "vectors": [
    [
     0.0,
     0.0,
     1.0
    ],
    [
     1.0,
     0.0,
     0.0
    ],
    [
     0.0,
     1.0,
     0.0
    ]
   ]
  },
  {
   "A": [
    [
     4.0,
     1.0,
     2.0,
     0.5
    ],
    [
     1.0,
     3.0,
     0.0,
     1.0
    ],
    [
     2.0,
     0.0,
     5.0,
     1.5
    ],
    [
     0.5,
     1.0,
     1.5,
     2.0
    ]
   ],
   "values": [
    7.192666377615422,
    3.506364555730739,
    2.523055330779222,
    0.7779137358746205
   ],
   "vectors": [
    [
     0.5718627245010698,
     0.20954922966921727,
     0.7314320104313823,
     0.30670728518826873
    ],
    [
     0.2817292803412171,
     0.806363554341934,
     -0.5043637170560643,
     0.12658464261059713
    ],
    [
     0.7212113858081275,
     -0.30870474772887335,
     -0.2347482064569622,
     -0.5739763020156956
    ],
    [
     0.2710272567572383,
     -0.45887723554751864,
     -0.394357369144963,
     0.7486375452727289
    ]
   ]
  }
 ],
 "nearest_rank": {
  "cases": [
   [
    0.05,
    15
   ],
   [
    0.3,
    20
   ],
   [
    0.4,
    20
   ],
   [
    0.5,
    35
   ],
   [
    0.95,
    50
   ],
   [
    1.0,
    50
   ]
  ],
  "values": [
   15,
   20,
   35,
   40,
   50
  ]
 },
 "principal_angle": [
  [
   [
    1.0,
    0.0
   ],
   [
    0.0,
    1.0
   ],
   1.5707963267948966
  ],
  [
   [
    1.0,
    0.0
   ],
   [
    1.0,
    1.0
   ],
   0.7853981633974484
  ],
  [
   [
    1.0,
    2.0,
    3.0
   ],
   [
    1.0,
    2.0,
    3.1
   ],
   0.01563556473211043
  ],
  [
   [
    0.0,
    0.0
   ],
   [
    1.0,
    0.0
   ],
   1.5707963267948966
  ]
 ],
 "residual_trend": {
  "idx": [
   0,
   1,
   2,
   3,
   4
  ],
  "resid": [
   0.1,
   -0.2,
   0.05,
   0.3,
   -0.1
  ],
  "slope": 0.01
 },
 "solve": {
  "X": [
   [
    1.0,
    1.0
   ],
   [
    1.0,
    2.0
   ],
   [
    1.0,
    3.0
   ],
   [
    1.0,
    4.0
   ],
   [
    1.0,
    5.0
   ],
   [
    1.0,
    6.0
   ]
  ],
  "beta": [
   -0.9466652473663719,
   2.994285353850642
  ],
  "ridge": 1e-06,
  "y": [
   2.1,
   4.9,
   8.2,
   10.9,
   14.1,
   17.0
  ]
 },
 "welford": {
  "m2": 3943.5999999999995,
  "mean": 26.200000000000003,
  "n": 10,
  "var": 438.1777777777777,
  "xs": [
   10,
   11,
   9,
   10,
   50,
   52,
   49,
   51,
   10,
   10
  ]
 },
 "welford_cov": {
  "c": [
   [
    10.0,
    -2.0
   ],
   [
    -2.0,
    21.200000000000003
   ]
  ],
  "cov": [
   [
    2.5,
    -0.5
   ],
   [
    -0.5,
    5.300000000000001
   ]
  ],
  "mean": [
   3.0,
   3.6
  ],
  "n": 5,
  "rows": [
   [
    1.0,
    2.0
   ],
   [
    2.0,
    4.0
   ],
   [
    3.0,
    7.0
   ],
   [
    4.0,
    4.0
   ],
   [
    5.0,
    1.0
   ]
  ]
 },
 "wilson": [
  [
   0,
   1,
   0.0,
   0.7934567085261071
  ],
  [
   1,
   1,
   0.2065432914738929,
   1.0
  ],
  [
   5,
   10,
   0.23658959361548731,
   0.7634104063845126
  ],
  [
   27,
   30,
   0.7437855868473339,
   0.9654007400402839
  ],
  [
   30,
   30,
   0.8864829086095221,
   1.0
  ],
  [
   34,
   34,
   0.8984820937803899,
   1.0
  ],
  [
   35,
   35,
   0.9010957324106112,
   1.0
  ],
  [
   99,
   100,
   0.9455124752390652,
   0.9982326134344527
  ]
 ]
}
